#
## dnf tasks: install/configure base softwares and repositories.
#

## Install softwares
- name: install qemu-guest-agent
  become: true
  ansible.builtin.dnf:
    name: qemu-guest-agent
    state: present

- name: install vim
  become: true
  dnf:
    name: vim
    state: present

- name: install nmap
  become: true
  dnf:
    name: nmap
    state: present

- name: install wget
  become: true
  dnf:
    name: wget
    state: present

## Start softwares at boot
- name: start qemu-guest-agent
  become: true
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
    enabled: yes
