---
# tasks file for common
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"  ## declared in hosts file
    use: systemd

- name: Package Config
  ansible.builtin.include_tasks: packages.yml
  tags: packages

- name: Service Config
  ansible.builtin.include_tasks: services.yml
  tags: services

- name: User Config
  ansible.builtin.include_tasks: users.yml
  tags: users

- name: Firewall Config
  ansible.builtin.include_tasks: firewalld.yml  
  tags: firewall
