---
# tasks file for common
- name: User Config
  ansible.builtin.include_tasks: users.yml
  tags: users

- name: Package Config
  ansible.builtin.include_tasks: packages.yml
  tags: packages

- name: Service Config
  ansible.builtin.include_tasks: services.yml
  tags: services

- name: Firewall Config
  ansible.builtin.include_tasks: firewalld.yml  
  tags: firewall
