## Install/configure base softwares and repositories.
- name: Package Config block
  block:
  - name: install base softwares
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items: "{{ base_packages }}"

  - name: remove unnecessary packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: absent
    with_items: "{{ removed_packages }}"
  become: true    
  tags: packages
