## Base configuration
- name: Service Config block
  block:
  - name: configure SSH
    ansible.builtin.copy:
      dest: /etc/ssh/sshd_config
      src: sshd_config
      owner: root
      group: root
      mode: 0600
    notify: reload SSH

  - name: start/enable base services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: "{{ base_services }}"
  become: true
  tags: services

# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
  
