## Base configuration
- name: start/enable base services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ base_services }}"

# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes

