---
# Setup NFS mounts and jellyfin container
- name: Service Config block
  tags: services
  block:
    - name: Create /mnt/jellyfin
      become: true
      ansible.builtin.file:
        path: /mnt/jellyfin
        state: directory

    - name: Mount jellyfin NFS volume
      become: true
      ansible.posix.mount:
        src: 192.168.4.11:/ssd_mirror/jellyfin
        path: /mnt/jellyfin
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

    - name: Create /mnt/media
      become: true
      ansible.builtin.file:
        path: /mnt/jellyfin
        state: directory

    - name: Mount media NFS volume
      become: true
      ansible.posix.mount:
        src: 192.168.4.11:/hdd_mirror/media
        path: /mnt/media
        opts: ro,sync,hard
        state: mounted
        fstype: nfs

    - name: Start jellyfin container
      containers.podman.podman_container:
        name: jellyfin
        image: docker.io/jellyfin/jellyfin
        network: host
        mount:
          - "type=bind,source=/mnt/media,destination=/media,ro=true"
          - "type=bind,source=/mnt/jellyfin/cache,destination=/cache,rw=true"
          - "type=bind,source=/mnt/jellyfin/config,destination=/config,rw=true"
        rm: true
        state: started

# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
