- name: Service Config block
  block:
  - name: create /mnt/jellyfin
    become: true
    ansible.builtin.file:
      path: /mnt/jellyfin
      state: directory

  - name: mount jellyfin NFS volume
    become: true
    ansible.posix.mount:
      src: 192.168.4.11:/ssd_mirror/jellyfin
      path: /mnt/jellyfin
      opts: rw,sync,hard
      state: mounted
      fstype: nfs

  - name: create /mnt/media
    become: true
    ansible.builtin.file:
      path: /mnt/jellyfin
      state: directory

  - name: mount media NFS volume
    become: true
    ansible.posix.mount:
      src: 192.168.4.11:/hdd_mirror/media
      path: /mnt/media
      opts: rw,sync,hard
      state: mounted
      fstype: nfs

  - name: start jellyfin container
    containers.podman.podman_container:
      name: jellyfin
      image: docker.io/jellyfin/jellyfin
      network: host
      mount:
        - "type=bind,source=/mnt/media,destination=/media,ro=true"
        - "type=bind,source=/mnt/jellyfin/cache,destination=/cache,rw=true"
        - "type=bind,source=/mnt/jellyfin/config,destination=/config,rw=true"
      rm: true
      state: started
  tags: services

# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
  
