## Base configuration
- name: Service Config block
  block:
  - name: create /mnt/jellyfin
    ansible.builtin.file:
      path: /mnt/jellyfin
      state: directory
      group: sudo
      mode: 0775

  - name: mount jellyfin NFS volume
    ansible.posix.mount:
      src: 192.168.4.11:/ssd_mirror/jellyfin
      path: /mnt/jellyfin
      opts: rw,sync,hard
      state: mounted
      fstype: nfs
  become: true
  tags: services

# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
  
