---
# tasks file for jellyfin role
- name: Service Config
  ansible.builtin.include_tasks: jellyfin_services.yml
  tags: services

- name: Firewall Config
  ansible.builtin.include_tasks: jellyfin_firewalld.yml  
  tags: firewall