---
- name: User Config block
  become: true
  tags: users
  block:
    - name: Add users to jellyfin group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: jellyfin
        append: true
      with_items: "{{ jellyfin_users }}"

    - name: Add users to jellyfin group on NFS server
      ansible.builtin.user:
        name: "{{ item }}"
        groups: jellyfin
        append: true
      with_items: "{{ jellyfin_users }}"
      delegate_to: "{{ nfs_server }}"
      notify: Reload NFS

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
