---
# vars file for proxmox role
proxmox_packages:
  - nfs-kernel-server

proxmox_services:
  - nfs-kernel-server

proxmox_ports:
  - 8006/tcp # proxmox web app
  - 2049/tcp # nfs

nfs_mounts:
  - { path: "/hdd_mirror/media", owner: chasty2,
      group: jellyfin, mode: "0770" }
  - { path: "/ssd_mirror/jellyfin", owner: ansible,
      group: jellyfin, mode: "0770" }

## These groups/users must also specified in the NFS client roles
nfs_groups:
  - { name: "jellyfin", gid: "2000" }

jellyfin_users:
  - ansible
  - chasty2
