---
# tasks file for proxmox role

# Groups made in common role, users added to groups by roles that employ them
# - name: User Config
#   ansible.builtin.include_tasks: proxmox_users.yml
#   tags: users

- name: Package Config
  ansible.builtin.include_tasks: proxmox_packages.yml
  tags: packages

- name: Service Config
  ansible.builtin.include_tasks: proxmox_services.yml
  tags: services

- name: Firewall Config
  ansible.builtin.include_tasks: proxmox_firewalld.yml
  tags: firewall
