## Base configuration
- name: Service Config block
  become: true
  tags: services
  block:
    - name: Configure NFS
      ansible.builtin.copy:
        dest: /etc/exports
        src: nfs_exports
        owner: root
        group: root
        mode: "0644"
      notify: Reload NFS

    - name: Set permissions of NFS mounts ## declared in proxmox vars
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        recurse: true
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items: "{{ nfs_mounts }}"
      notify: Reload NFS

    - name: Start/enable base services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items: "{{ proxmox_services }}"


# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
