## Base configuration
- name: Service Config block
  block:
  - name: configure NFS
    ansible.builtin.copy:
      dest: /etc/exports
      src: nfs_exports
      owner: root
      group: root
      mode: 0644
    notify: reload NFS

  - name: start/enable base services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: "{{ proxmox_services }}"
  become: true
  tags: services

# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
  
