- name: User Config block
  become: true
  tags: users
  block:
    - name: Create NFS groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      with_items: "{{ nfs_groups }}"

    - name: Add users to jellyfin group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: jellyfin
        append: true
      with_items: "{{ jellyfin_users }}"
