#
## configure firewalld on proxmmox hosts
#
- name: open permitted ports on firewalld zone 'internal'
  become: true
  ansible.posix.firewalld:
    zone: internal
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ proxmox_ports }}"
  tags: firewall