---
# vars file for common
common_groups:
  - { name: "ansible", gid: "1000"}
  - { name: "chasty2", gid: "1001" }
  - { name: "podman", gid: "2004"}
  # - { name: "jellyfin", gid: "2000" }
  # - { name: "proxy", gid: "2001" }
  # - { name: "foundry", gid: "2002"}
  # - { name: "postgres", gid: "2003"}
  # - { name: "pihole", gid: "2005"}

common_service_users:
  - { name: "ansible", uid: "1000", gid: "1000"}
  - { name: "podman", uid: "2004", gid: "2004"}

common_ssh_keys:
  - { name: "chasty2", public_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIBbguD7QoF6kNwqKRaxIkVAy6XwMxKJZ5vK71T/0mg1 abzan SSH key" }
  - { name: "ansible", public_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGj0KFGQuRcbeX+P9z/O+nYDSu7NRSCx0BMDg5TwF5QJ CrowsNet ansible user" }

common_packages:
  - sudo
  - vim
  - nmap
  - wget
  - firewalld
  - less
  - nfs-common
  - htop
  - nmon
  - rsyslog
  - bind9-dnsutils
  - cron
  - ncdu
  - tmux

common_services:
  - firewalld
  - sshd
  - cron

common_removed_packages:
  - ufw
  - vim-tiny

# disabled_services:
#   - ufw

common_permitted_ports:
  - ssh

common_closed_ports:
  - dhcpv6-client
  - mdns
  - samba-client

common_permitted_networks:
  - 192.168.4.0/22
