---
# Configure firewalld
- name: Firewall Config Block
  become: true
  tags: firewall
  block:
    - name: Open permitted ports on firewalld zone 'internal'
      ansible.posix.firewalld:
        zone: internal
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items: "{{ common_permitted_ports }}"

    - name: Close unnecessary ports on firewalld zone 'internal'
      ansible.posix.firewalld:
        zone: internal
        service: "{{ item }}"
        state: disabled
        permanent: true
        immediate: true
      with_items: "{{ common_closed_ports }}"

    - name: Add permitted network(s) to firewalld zone 'internal'
      ansible.posix.firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items: "{{ common_permitted_networks }}"
