---
## Install/configure base softwares and repositories.
- name: Package Config Block
  become: true
  tags: packages
  block:
    - name: Install base softwares
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_packages }}"

    - name: Remove unnecessary packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ common_removed_packages }}"
