---
## Base configuration
- name: Service Config Block
  become: true
  tags: services
  block:
    - name: Configure SSH
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/common.conf
        src: sshd_common
        owner: root
        group: root
        mode: "0600"
      notify: Reload SSH

    - name: Set timezone
      community.general.timezone:
        name: America/Chicago
      notify: Restart crond

    - name: Start/enable base services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items: "{{ base_services }}"


# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
