---
# Setup NFS mounts and npm container
- name: Service Config block
  become: true
  tags: services
  block:
    - name: Create /mnt/proxy
      ansible.builtin.file:
        path: /mnt/proxy
        state: directory
        owner: ansible
        group: proxy
        mode: "0770"

    - name: Mount proxy NFS volume
      ansible.posix.mount:
        src: 192.168.4.11:/ssd_mirror/proxy
        path: /mnt/proxy
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

    ## TODO: Mount jellyfin logs for fail2ban?

    ## TODO: Configure rootless mode
    - name: Start npm container
      containers.podman.podman_container:
        name: proxy
        network: host
        image: docker.io/jc21/nginx-proxy-manager:latest
        env:
          DISABLE_IPV6: true
        mount:
          - "type=bind,source=/mnt/proxy/data,destination=/data,rw=true"
          - "type=bind,source=/mnt/proxy/letsencrypt,destination=/etc/letsencrypt,rw=true"
        state: started
        restart_policy: on-failure:3

# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
