---
# tasks file for foundry role
- name: User Config
  ansible.builtin.include_tasks: foundry_users.yml
  tags: users

- name: Service Config
  ansible.builtin.include_tasks: foundry_services.yml
  tags: services

- name: Firewall Config
  ansible.builtin.include_tasks: foundry_firewalld.yml
  tags: firewall
