---
# tasks file for jellyfin role
- name: User Config
  ansible.builtin.include_tasks: jellyfin_users.yml
  tags: users

- name: Service Config
  ansible.builtin.include_tasks: jellyfin_services.yml
  tags: services

- name: Firewall Config
  ansible.builtin.include_tasks: jellyfin_firewalld.yml
  tags: firewall
