---
- name: Open permitted ports on firewalld zone 'internal'
  become: true
  ansible.posix.firewalld:
    zone: internal
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items: "{{ proxmox_ports }}"
  tags: firewall
