---
## NFS configuration
- name: Service Config Block
  become: true
  tags: services
  block:
    - name: Configure NFS directories ## declared in proxmox vars
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items: "{{ nfs_mounts }}"
      notify: Reload NFS

    - name: Configure NFS exports
      ansible.builtin.template:
        dest: /etc/exports
        src: nfs_exports.j2
        owner: root
        group: root
        mode: "0644"
      notify: Reload NFS

    - name: Start/enable base services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items: "{{ proxmox_services }}"


# - name: disable unnecessary services
#   become: true
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   with_items: "{{ disabled_services }}"
#   ignore_errors: yes
