---
## NFS configuration
- name: Service Config Block
  become: true
  tags: services
  block:
    - name: Configure NFS directories ## declared in proxmox vars
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items: "{{ proxmox_nfs_mounts }}"
      notify: Reload NFS

    - name: Configure NFS exports
      ansible.builtin.template:
        dest: /etc/exports
        src: nfs_exports.j2
        owner: root
        group: root
        mode: "0644"
      notify: Reload NFS

    - name: Schedule backups
      ansible.builtin.cron:
        name: "{{ item.name }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        weekday: "{{ item.weekday }}"
        job: "{{ item.job }}"
        user: root
        state: present
      loop: "{{ proxmox_cron_jobs }}"

    - name: Start/enable base services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items: "{{ proxmox_services }}"
