---
- name: User Config Block
  become: true
  tags: users
  block:
    # Allow admin users to view container data (on esper) and push files to /media
    # Having the podman user own data mounted to containers, but stored on esper, makes permissions nicer inside the containers
    - name: Add admin users to podman group
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: podman
        append: true
      with_items: "{{ admin_users }}"

    - name: Copy backup script to root directory
      ansible.builtin.template:
        src: backup_script.j2
        dest: /root/backup.sh
        owner: root
        group: root
        mode: "0700"
