---
# Setup NFS mounts and postgres container
- name: Service Config Block (root user)
  become: true
  tags: services
  block:
    - name: Create /mnt/postgres
      ansible.builtin.file:
        path: /mnt/postgres
        state: directory
        owner: podman
        group: podman
        mode: "0770"

    - name: Mount postgres NFS volume
      ansible.posix.mount:
        src: 192.168.4.11:/ssd_mirror/postgres
        path: /mnt/postgres
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

- name: Service Config Block (podman user)
  remote_user: podman
  tags: services
  block:
    - name: Create mount point for postgres container data
      ansible.builtin.file:
        path: /mnt/postgres/pgdata
        state: directory
        owner: podman
        group: podman
        mode: "0700"

    - name: Start postgres container
      containers.podman.podman_container:
        name: postgres
        image: docker.io/postgres:15.8
        # Preserve OS-level user permissions by running as podman user, mapped to same uid in postgres container
        user: podman
        userns: "keep-id"
        ports:
          - "5432:5432"
        # pgdata is mounted one directory lower than the default due to perm setting behavior at init
        env:
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          PGDATA: "/var/lib/postgresql/data/pgdata"
        # /etc/passwd of OS mounted read-only to container as workaround to ensure podman user exists in /etc/passwd at init
        mount:
          - "type=bind,source=/mnt/postgres/pgdata,destination=/var/lib/postgresql/data/pgdata,rw=true"
          - "type=bind,source=/etc/passwd,destination=/etc/passwd,ro=true"
        state: started
        # bug in podman 4.9 with userns: keep-id and restart_policy: always
        # restart_policy: always
