---
# vars file for common
base_packages:
  - sudo
  - vim
  - nmap
  - wget
  - firewalld
  - less
  - nfs-common
  - htop
  - nmon
  - rsyslog
  - bind9-dnsutils

base_services:
  - firewalld
  - sshd

removed_packages:
  - ufw

# disabled_services:
#   - ufw

permitted_ports:
  - ssh

closed_ports:
  - dhcpv6-client
  - mdns
  - samba-client

permitted_networks:
  - 192.168.4.0/22
