- name: Is ansible working?
  hosts: localhost
  tasks:
    - name: Ping localhost
      ansible.builtin.ping:

- name: Test components
  hosts: test
  roles:
    - common
    - virtual
    - podman
    - jellyfin
