- name: Virtual Machines
  hosts: virtual
  roles:
    - common
    - virtual

- name: Public-facing Machines
  hosts: dmz
  roles:
    - public

- name: SSH Bastion
  hosts: gate
  roles:
    - gate

- name: Web Proxy
  hosts: proxy
  roles:
    - proxy

# As of now, all web services depend on podman
- name: Web services
  hosts: bailey
  roles:
    - podman
    - jellyfin
    - foundry
