- name: Virtual Machines
  hosts: virtual
  roles:
    - common
    - virtual

- name: Public-facing Machines
  hosts: gate
  roles:
    - public
    - gate  # configure fail2ban for sshd

# As of now, all web services depend on podman
- name: Web services
  hosts: bailey
  roles:
    - podman
    - jellyfin
