---
# tasks file for virtual role
- name: Package Config
  ansible.builtin.include_tasks: virtual_packages.yml
  tags: packages

- name: Service Config
  ansible.builtin.include_tasks: virtual_services.yml
  tags: services