---
# System-level configuration for common role
- name: System Config Block
  become: true
  tags: system
  block:
    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}" ## See hosts file for naming convention
        use: systemd
