---
# vars file for proxmox role
proxmox_packages:
  - nfs-kernel-server

proxmox_services:
  - nfs-kernel-server

proxmox_ports:
  - 8006/tcp # proxmox web app
  - 2049/tcp # nfs

nfs_mounts:
  - { path: "/hdd_mirror/media", owner: chasty2,
      group: jellyfin, mode: "0770" }
  - { path: "/ssd_mirror/jellyfin", owner: podman,
      group: jellyfin, mode: "0770" }
  - { path: "/ssd_mirror/proxy", owner: ansible,
      group: proxy, mode: "0770"}
  - { path: "/ssd_mirror/foundry", owner: ansible,
      group: foundry, mode: "0770"}
  - { path: "/ssd_mirror/postgres", owner: ansible,
      group: postgres, mode: "0770"}
