## fail2ban configuration
- name: Service Config block
  become: true
  tags: services
  block:
    - name: Configure fail2ban defaults
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.local
        src: jail_local
        owner: root
        group: root
        mode: "0640"
      notify: Reload fail2ban

    # delete defaults-debian.conf

    - name: Configure sshd jail
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.d/sshd.conf
        src: jail_sshd
        owner: root
        group: root
        mode: "0640"
      notify: Reload fail2ban

    - name: Start/enable fail2ban services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items: "{{ fail2ban_services }}"
