---
# vars file for common
all_groups:
  - { name: "chasty2", gid: "1001" }
  - { name: "jellyfin", gid: "2000" }
  - { name: "proxy", gid: "2001" }
  - { name: "foundry", gid: "2002"}
  - { name: "postgres", gid: "2003"}
  - { name: "podman", gid: "2004"}

admin_users:
  - { name: "chasty2", uid: "1001", gid: "1001" }

service_users:
  - { name: "podman", uid: "2004", gid: "2004"}

# podman user has the same public key as the ansible user
# This is because I am using ssh to create a login session for the podman user to run containers
ssh_keys:
  - { name: "chasty2", public_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIBbguD7QoF6kNwqKRaxIkVAy6XwMxKJZ5vK71T/0mg1 abzan SSH key" }
  - { name: "ansible", public_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGj0KFGQuRcbeX+P9z/O+nYDSu7NRSCx0BMDg5TwF5QJ CrowsNet ansible user" }

base_packages:
  - sudo
  - vim
  - nmap
  - wget
  - firewalld
  - less
  - nfs-common
  - htop
  - nmon
  - rsyslog
  - bind9-dnsutils
  - cron
  - ncdu

base_services:
  - firewalld
  - sshd
  - cron

removed_packages:
  - ufw
  - vim-tiny

# disabled_services:
#   - ufw

permitted_ports:
  - ssh

closed_ports:
  - dhcpv6-client
  - mdns
  - samba-client

permitted_networks:
  - 192.168.4.0/22
