---
# Setup NFS mounts and postgres container
- name: Service Config Block (root user)
  become: true
  tags: services
  block:
    - name: Create /mnt/postgres
      ansible.builtin.file:
        path: /mnt/postgres
        state: directory
        owner: ansible
        group: postgres
        mode: "0770"

    - name: Mount postgres NFS volume
      ansible.posix.mount:
        src: 192.168.4.11:/ssd_mirror/postgres
        path: /mnt/postgres
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

    - name: Create mount point for postgres container data
      ansible.builtin.file:
        path: /mnt/postgres/data
        state: directory
        mode: "0700"

    - name: Create mount point for postgres container logs
      ansible.builtin.file:
        path: /mnt/postgres/logs
        state: directory
        mode: "0755"

    # NOTE: This is a rooted container. It will start on boot due to restart=always
    - name: Create postgres container
      containers.podman.podman_container:
        name: postgres
        image: docker.io/postgres:15.8
        network: host
        env:
          POSTGRES_PASSWORD: "{{ postgres_password }}"
        mount:
          - "type=bind,source=/mnt/postgres/data,destination=/var/lib/postgresql/data,rw=true"
          - "type=bind,source=/mnt/postgres/logs,destination=/var/log/postgresql,rw=true"
        state: started
        restart_policy: always
