---
# Setup NFS mounts and npm container
- name: Service Config Block (root user)
  become: true
  tags: services
  block:
    - name: Create /mnt/proxy
      ansible.builtin.file:
        path: /mnt/proxy
        state: directory
        owner: podman
        group: podman
        mode: "0770"

    - name: Mount proxy NFS volume
      ansible.posix.mount:
        src: 192.168.4.11:/ssd_mirror/proxy
        path: /mnt/proxy
        opts: rw,sync,hard
        state: mounted
        fstype: nfs

  ## TODO: Mount jellyfin logs for fail2ban?
- name: Service Config Block (podman user)
  remote_user: podman
  tags: services
  block:
    - name: Create mount points for proxy container
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: podman
        group: podman
        mode: "0770"
      loop:
        - "/mnt/proxy/data"
        - "/mnt/proxy/letsencrypt"

    - name: Start npm container
      containers.podman.podman_container:
        name: proxy
        ports:
          - "81:81"
          - "80:80"
          - "443:443"
        userns: host
        image: docker.io/jc21/nginx-proxy-manager:latest
        env:
          DISABLE_IPV6: true
        mount:
          - "type=bind,source=/mnt/proxy/data,destination=/data,rw=true"
          - "type=bind,source=/mnt/proxy/letsencrypt,destination=/etc/letsencrypt,rw=true"
        state: started
        restart_policy: on-failure:3
