---
# vars file for proxmox role
proxmox_packages:
  - nfs-kernel-server
  - tmux

proxmox_services:
  - nfs-kernel-server

proxmox_ports:
  - 8006/tcp # proxmox web app
  - 2049/tcp # nfs

# 770 on this directory restricts access to authorized users, but
# won't affect permissions of container data within the directory
proxmox_nfs_mounts:
  - { path: "/hdd_mirror/media", owner: podman,
      group: jellyfin, mode: "0770" }
  - { path: "/ssd_mirror/jellyfin", owner: podman,
      group: jellyfin, mode: "0770" }
  - { path: "/ssd_mirror/proxy", owner: podman,
      group: proxy, mode: "0770" }
  - { path: "/ssd_mirror/foundry", owner: podman,
      group: foundry, mode: "0770" }

# 0 = Sunday, 1 = Monday, ..., 6 = Saturday
proxmox_cron_jobs:
  - { name: "Backup jellyfin config data, daily at 12AM",
      minute: "0",
      hour: "0",
      weekday: "*",
      job: "proxmox-backup-client backup jellyfin.pxar:/ssd_mirror/jellyfin --repository root@pam@192.168.4.12:backup --ns jellyfin"
  }
  - { name: "Backup proxy config data, daily at 1215AM",
      minute: "15",
      hour: "0",
      weekday: "*",
      job: "proxmox-backup-client backup proxy.pxar:/ssd_mirror/proxy --repository root@pam@192.168.4.12:backup --ns proxy"
  }
  - { name: "Backup foundry config data, daily at 1230AM",
      minute: "30",
      hour: "0",
      weekday: "*",
      job: "proxmox-backup-client backup foundry.pxar:/ssd_mirror/foundry --repository root@pam@192.168.4.12:backup --ns foundry"
  }
  - { name: "Backup media, Monday at 3AM",
      minute: "0",
      hour: "3",
      weekday: "1",
      job: "proxmox-backup-client backup media.pxar:/hdd_mirror/media --repository root@pam@192.168.4.12:backup --ns media"
  }
  - { name: "Trim ssd_mirror pool, Wednesday at 3AM",
      minute: "0",
      hour: "3",
      weekday: "3",
      job: "zpool trim ssd_mirror"
  }

proxmox_pbs_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35613132396665333931366239316161376466313866613131393263383533323865303730383639
  3664623238306534353163633565613932613564633239650a376533343866333930666333353135
  62346138653065666665373639616266633666393566323136326331313437316335376431656564
  3535623236353562380a313064663435326338323462663566303732396165663034343639383132
  66313830636538613961353733616162653739626465366437363137663435383465
